image: node:4.2.2

cache:
  paths:
  - bower_components
  - node_modules

build:
  script:
  - npm install -g bower
  - npm install -g gulp
  - bower install --allow-root
  - npm install
  - npm run build
  artifacts:
    paths:
    - build
