image: node:8-alpine

cache:
  paths:
  - node_modules

build:
  script:
  - apk add --update git
  - yarn
  - yarn build
  - cd build/
  - mv langs plugins skins themes hooks.php jquery.tinymce.min.js tinymce.min.js ../
  - cd ../
  artifacts:
    paths:
    - langs
    - plugins
    - skins
    - themes
    - hooks.php
    - jquery.tinymce.min.js
    - tinymce.min.js
