image: node:4.2.2

cache:
  paths:
  - bower_components
  - node_modules

build:
  script:
  - npm install -g bower
  - npm install -g gulp
  - bower install --allow-root
  - npm install
  - npm run build
  - cd build/
  - mv langs plugins skins themes hooks.php jquery.tinymce.min.js tinymce.jquery.min.js tinymce.min.js ../
  - cd ../
  artifacts:
    paths:
    - langs
    - plugins
    - skins
    - themes
    - hooks.php
    - jquery.tinymce.min.js
    - tinymce.jquery.min.js
    - tinymce.min.js
