language: node_js

node_js:
  - "6"

install:
  - npm install -g bower
  - bower install
  - npm install

script:
  - npm run build

before_deploy:
  - cd build/
  - zip -r tinymce *

deploy:
  provider: releases
  api_key:
    secure: abBq0of0lmn4j+09pEyB2A+EaZQLdMHmnS5t1GGuHbEDxZpziDr/XEMXV8iGdWvP889MLWn48+9BEpmPWUSKTts87rMkw7tnOsisqv7JAmrS/rxEyOUQE2EqGGHWUlrv1RM2wk2aNaeVLyhlbHU6s510tMEUgtubt5ZJpHcLaAxV73WrxLBmOWiaX0rz8yoXYSZa5NbhjrH/UcXCp2tcQMlKFdB9i4Sl5cMAqQnenZHwrNGoPIgnvQMn4y463NdqeqdqXyS7U4Z82+uilIeWqE7twzG0BVR9Oa2Emj72DzSyWh4avNBuoGGp6hU+T+i3EkRvDq6RxfZn8Z+8eWClecR2SzfnhrKPJ8r2CEXx38NMGrdOGIpXD1Z90yeJZMbhh3yUh4PbjkadEaogWW31SO9YLGIM//dDVkS0p1600TQmcKvU0Re8vkXuR86HbRw6tSKtm6qiwOYPK77vJpK2wLprShl43pegvsmWdJ+9Or6r7QcsRxRm2UssMSXJSNWJil9CsWRWDjWDMWb7xkeUH5GwX5irNKDPq9ePIaASGZi75A9mt15Fr1jNbgXyCcb/2XvLS7KVTCVccjRfvUHVslrreFK/Bg7gi1W0wST3bQ1Ua33ptIt3FdnOCrmF6h7b9g+YaSjDnqPWgDkR1Fx4r5NHuXWKpqAUtn6sQ+dvD6Q=
  file: tinymce.zip
  on:
    tags: true
