language: node_js

node_js:
  - "6"

install:
  - npm install -g bower
  - bower install
  - npm install

script:
  - npm run build

before_deploy:
  - cd build/
  - zip -r tinymce *

deploy:
  provider: releases
  api_key:
    secure: hAJ0SbIAIOdj5B4hn7GMU1hHH7pFdUeu+tcrBBWFt63uxhUvKJiP8E+v2nbUEBt1LjhOF8B7795vCCxkmVHIgKED1g4RCl8DVDRMoqEph/uan20ZWZdCj6wNo0ukW0FGsIS7mn5xycgW1PEf4slulzmqGPTB7mHAF5Q9+RUA5G6YCmkJPv9QL0bVa/7N/thwD/NVYuidB+Z+ErEJyDYt8055wrY8Ye58bKy2imhPjJp2bBe20W3K3OkVEWLxtaIIvS0UUYKkKxf7oUxBTmlGqzRuoq0nJ/NurRbUf8zwaKmIMRQGE1A9kHybzR/JXX1npDUs3KwyEuk3ZEMT1TN/5377GBdtQ4How3wLatgjHZnEg6vj7qZQ/xAfleTVQmY57E161Q8F2Lr4ecZGILHul7Qy0Ah74bmkNr3XRQBQUPy5QlDujrI6uwpV9V1CVUTb39Ni6HUTY8s1cvawXQFTQRoSy3wW639x4cbvFr4hk+dGpGrjWj7DSvSpQlH+nr+uSs64sAvNfenn6HkFrzOgEiTq/hX9Zi9p5nLLkEEUw3RdCEQg4X0gV8WNwI4oUMstMwFHNeZ3TJwfjJjY0Y4COf78AiyDksvHP1XQZMHsYrY5DOqjxa8J0Ew8HtByfsweI/VLlmPJ52Q+rnCGLFRsUiueWN6uQgBawOyyYDsnma0=
  file: tinymce.zip
  on:
    tags: true
