language: node_js

node_js:
  - "6"

install:
  - npm install -g bower
  - bower install
  - npm install

script:
  - npm run build

before_deploy:
  - cd build/
  - zip -r tinymce *

deploy:
  provider: releases
  api_key:
    secure: "psrRYpVMFpN+fC6ETCYspKOz/zfnETvsEl4FuO/VjbuUfaIGrbemP1GT2A+ahQ2ux8JQkfsb0Wx74bbS5VLMGw1kSiWFlma2RxgqEjCXfRFlaRcz0WCyp3sJv74FhBYw8h3lednPWswcY6GM1ImMZJst8yzPFurkgb89oxJnA7nO+3k88GBHIEAaoSoBM3lzmmDOwFXKmU8iQMSSSU+9HzZ/aFRYdDDlhEyZhVTNHCngdgNVjjLLQn2oquov51mt3rqBpIQXFsHox62SLuufl53GkGmbtzF/2YTTP0SpkJWoCf7JgxlueefCTjf/yezj7Odw6Folsgt5cUini1K1+02EHYgc6w1P/9OVfXWKcco4QhxJSPjtSx/zN0ZDH4S60J1AY1xfeQ2J9Wguhx5rLEMMask2dK9lyuaDgfUwRU2m2XnXjhqGE3z+Vv2B/GZgCsFWV8W4FMIqkKpf1lxnt9mhl6asB3MWa8FMnTbRdC1Ahe6FmUKh3kAryqm7EIfUHUkjktF1SUr6dR8Zb5mvolb5RPbH3zXXl9w/UpZqNrSgkPQf1hKFEqD3WpimZgd7dI/AqaoA1PkpsfLSPRVZ+F9bE5QfAXGpN9Nx4nHEB6SdFhu06Y607gIjDxRmlSw1olkblZX1WLHB+c3U9GAisuSCq66FF7zabkK5LtvQ9i4="
  file: tinymce.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
